parameters:
  name: ''
  runtimeIdentifier: 'win-x64'
  vmImage: 'windows-latest'
  dependsOn: []

stages:
- stage: '${{ parameters.name }}'

  variables:
    buildConfiguration: 'Release'
    solutionFile: $(Build.SourcesDirectory)/src/Todo.CLI.sln
    projectDirectory: $(Build.SourcesDirectory)/src/Todo.CLI/
    outputDirectory: $(Build.ArtifactStagingDirectory)/${{ parameters.runtimeIdentifier }}/
    artifactName: 'todo.$(Build.BuildNumber).${{ parameters.runtimeIdentifier }}'

  dependsOn: ${{ parameters.dependsOn }}
  jobs:
  - job: 'publish_${{ parameters.name }}_job'
    pool:
      vmImage: ${{ parameters.vmImage }}
    steps:
    - task: UseDotNet@2
      inputs:
        version: '8.0.x'
        includePreviewVersions: false

    - script: |
        dotnet restore $(projectDirectory)
        dotnet publish $(projectDirectory) \
          -c $(buildConfiguration) \
          -r ${{ parameters.runtimeIdentifier }} \
          -o $(outputDirectory) \
          /p:Version=$(Build.BuildNumber) \
          /p:PublishSingleFile=true \
          /p:PublishTrimmed=true \
          /p:IncludeNativeLibrariesForSelfExtract=true \
          /p:EnableCompressionInSingleFile=true \
          /p:DebugType=embedded \
          --self-contained true
      displayName: 'Publish as self-contained executable for ${{ parameters.runtimeIdentifier }}'

    - task: CopyFiles@2
      inputs:
        sourceFolder: '$(projectDirectory)'
        contents: 'appsettings.json'
        targetFolder: '$(outputDirectory)'
      displayName: 'Copy appsettings.json to output'

    - publish: '$(outputDirectory)'
      displayName: 'Publish artifact for ${{ parameters.runtimeIdentifier }}'
      artifact: '$(artifactName)'
