name: 0.2.0$(rev:.r)

trigger:
- master

pr:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  solutionFile: $(Build.SourcesDirectory)/src/Todo.CLI.sln

steps:
- task: UseDotNet@2
  inputs:
    version: '8.0.x'
    includePreviewVersions: false

- script: |
    dotnet restore $(solutionFile)
    dotnet build $(solutionFile) --configuration $(buildConfiguration) /p:Version=$(Build.BuildNumber)
    dotnet test $(solutionFile) --configuration $(buildConfiguration) --no-build
  displayName: 'Build and test solution'
  