name: 0.2.0$(rev:.r)

trigger:
- master

pr:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  solutionFile: $(Build.SourcesDirectory)/src/Todo.CLI.sln

steps:
- task: UseDotNet@2
  inputs:
    version: '8.0.x'
    includePreviewVersions: false

- script: |
    dotnet restore $(solutionFile)
  displayName: 'Restore dependencies'

- script: |
    dotnet build $(solutionFile) --configuration $(buildConfiguration) /p:Version=$(Build.BuildNumber)
  displayName: 'Build solution'

- script: |
    dotnet test $(solutionFile) \
      --configuration $(buildConfiguration) \
      --no-build \
      --logger trx \
      --results-directory "$(Agent.TempDirectory)/TestResults"
  displayName: 'Run unit tests'

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: VSTest
    testResultsFiles: '$(Agent.TempDirectory)/TestResults/*.trx'
    testRunTitle: 'Unit Tests - CI Build'
  